[package]
name = "herdr-caffeinate"
version = "0.1.0"
edition = "2024"
authors = [
  "Bo Kleynen",
]

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lints.rust]
non_ascii_idents = "deny"
redundant_imports = "deny"
missing_debug_implementations = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
ref_patterns = "warn"
undocumented_unsafe_blocks = "deny"
